Metrics/BlockLength:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BlockEndNewline:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false
