---
sudo: required
services:
  - docker

branches:
  only:
    - travis-poc

language: ruby

env:
  - DISTRO=centos-6-x64
  - DISTRO=centos-7-x64
  - DISTRO=debian-7-x64
  - DISTRO=debian-8-x64
  - DISTRO=ubuntu-server-1404-x64

install:
  - make
script:
  - make test-rspec
  - make test-integration
