---
sudo: required
services:
  - docker

branches:
  only:
    - travis-poc

language: ruby

env:
  - DISTRO=ubuntu-server-1404-x64

install:
  - make
script:
  - make test-rspec
  - make test-integration
