---
sudo: required
services:
  - docker

branches:
  only:
    - cleanup-ci

language: ruby

env:
  global:
    - TEST_SUITE=beaker
  matrix:
    - TEST_SUITE=intake
    - DISTRO=centos-6-x64
    - DISTRO=centos-7-x64
    - DISTRO=debian-7-x64
    - DISTRO=debian-8-x64
    - DISTRO=ubuntu-server-1204-x64
    - DISTRO=ubuntu-server-1404-x64

install:
  - make
script:
  - make test-$TEST_SUITE
