---
sudo: required
services:
  - docker

branches:
  only:
    - cleanup-ci

cache:
  bundler: true
  directories:
    - spec/fixtures/artifacts
    - spec/fixtures/modules

language: ruby

env:
  global:
    - TEST_SUITE=acceptance
  matrix:
    - TEST_SUITE=intake
    - TEST_SUITE=integration
    - DISTRO=centos-6-x64
    - DISTRO=centos-7-x64
    - DISTRO=debian-7-x64
    - DISTRO=debian-8-x64
    - DISTRO=ubuntu-server-1204-x64
    - DISTRO=ubuntu-server-1404-x64
    - DISTRO=opensuse-13-x64
matrix:
  allow_failures:
    - env: DISTRO=opensuse-13-x64

install:
  - bundle install --path .vendor
  - bundle exec rake spec_prep
script:
  - make test-$TEST_SUITE
